name: Testing package

on: push

jobs:
  lint:
    strategy:
      matrix:
        cmd:
          - black
          - flake8
          - isort
          - mypy
          - autoflake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "poetry"
      - name: Install deps
        run: poetry install
      - name: Run lint check
        run: poetry run pre-commit run -a ${{ matrix.cmd }}
  pytest:
    permissions:
      checks: write
      pull-requests: write
      contents: write
    strategy:
      matrix:
        py_version: ["3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest]
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v2
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.py_version }}"
          cache: "poetry"
      - name: Install deps
        run: poetry install
      - name: Download memphis docker-compose file
        run: |
          curl -s https://memphisdev.github.io/memphis-docker/docker-compose-dev.yml -o docker-compose.yaml
      - name: Run docker-compose file
        run: docker compose -f docker-compose.yaml -p memphis up -d
      - name: Run pytest check
        run: poetry run pytest -vv -n auto --cov="taskiq_memphis" .
      - name: Generate report
        run: poetry run coverage xml
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
        if: matrix.os == 'ubuntu-latest' && matrix.py_version == '3.9'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          verbose: true
      - name: Stop and remove running containers
        run: |
          docker compose down
